
default_platform(:android)

platform :android do
  desc "For Android Firebase distribution"
  lane :Firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --target lib/main_development.dart --split-per-abi"
    firebase_app_distribution(
      app: "1:24349726431:android:c3db9d3f3528134e14fb6a",
      groups: "qa-team, trusted-testers",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      testers: "mohamedabdelmonemfouad@gmail.com",
      release_notes: "New build is available for testing."
   )  
  end
end
